- alias: Set theme at startup
  trigger:
    event: start
    platform: homeassistant
  action:
    data:
      name: Me_Dark_Theme
    service: frontend.set_theme

- alias: Notify when lock batteries are low
  description: ''
  trigger: []
  condition:
    condition: or
    conditions:
    - below: '40'
      condition: numeric_state
      entity_id: sensor.basement_door_lock_battery
    - below: '40'
      condition: numeric_state
      entity_id: sensor.front_door_lock_battery
    - below: '40'
      condition: numeric_state
      entity_id: sensor.porch_door_lock_battery
  action:
    data:
      message: Door lock battery low!
    service: notify.notify

- alias: Notify when thermostat offline
  description: This can be used to more or less tell if the power is out, even if
    the generator is running.
  trigger:
    platform: state
    entity_id: climate.main_floor
    to: unavailable
  action:
    data:
      message: Downstairs thermostat went offline (maybe the power went out?)
    service: notify.notify

- alias: Notify when thermostat online
  description: This can be used to more or less tell if the power is back on, even
    if the generator is running.
  trigger:
    entity_id: climate.main_floor
    from: unavailable
    platform: state
  condition: []
  action:
    data:
      message: Downstairs thermostat back online (maybe the power came back on?)
    service: notify.notify

- alias: Notify on spare room motion
  description: Spare room motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.spare_room_motion_motion
    to: 'on'
  action:
    data:
      message: Spare room motion detected
    service: notify.mobile_app_iphone
